### PR TITLE
Feature/code

### PR DESCRIPTION
**Pull request by una**
Issue #58

### CODE REVIEW

**Comment by una** [comment]
Making the font smaller helps mitigate the issue of it feeling constrained by the other text in the paragraph. Looking over it again

**Comment by Snugug** [comment]
I'm cool with that, but that's not happening currently.

**Comment by Snugug** [comment]
We going to keep the left and right padding?

**Comment by una** [comment]
yes because we need the spacing between characters and the border for better legibility

**Comment by Snugug** [comment]
There's no more border

**Comment by una** [comment]
it still needs padding because there is a border between the background-color of the code and the background of the page (the edge of the element is a border) :)

**Pull request merged**
