### PR TITLE
Feature/em

### PR DESCRIPTION
**Pull request by una**
Issue #60

### CODE REVIEW

**Comment by una** [comment]
@Snugug isn't this font-style an inherent feature? Also, @britanyponvelle

**Comment by britanyponvelle** [comment]
I agree with wanting emphasized text to appear differently. Maybe assigning the test a different value (darker or lighter than the body text) would be more appropriate for this?

**Comment by Snugug** [comment]
@britanyponvelle Same comments involving color here that I do for #81; emphasized text can be used anywhere, not just within the body copy. That being said, do we want to set a color for this?

**Comment by britanyponvelle** [comment]
I hear what you're saying. Let's take out the color here as well

**Comment by una** [comment]
done :+1:

**Pull request merged**
