### PR TITLE
Feature/animation setup

### PR DESCRIPTION
**Pull request by una**
- two mixins for including animations on the fly
- Watson bezier variables (placeholders, can be refactored into a map structure later)
- animation map structure

### CODE REVIEW

**Comment by una** [comment]
Easing function map was addressed in description -- this is a placeholder for now until it is addressed how we will use them

**Comment by Snugug** [comment]
I'd like them in a map to begin with as we know we don't want them as bare variables.

**Comment by una** [comment]
@Snugug I think you were commenting on an older commit (91faebb)

**Comment by Snugug** [comment]
Even on the most current commit the easing values aren't in a map

**Comment by una** [comment]
In the last comment, please elaborate on 'this pattern'. I'm not familiar with that code base and what you are referencing specifically in the lines of code linked.

**Comment by Snugug** [comment]
@una it links to line 14-20 (well should be 14-19) of that codebase. Specifically this code:

```scss
    @if feature-exists(at-error) {
      @error 'You need to include a state for the `eq` mixin';
    }
    @else {
      @warn 'You need to include a state for the `eq` mixin';
    }
```

**Comment by Snugug** [comment]
@una Are you going to update this?

**Comment by ryanbrownhill** [comment]
YAY! :tada:

**Pull request merged**
